# Generated by Django 3.1.7 on 2021-03-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biocarb21', '0002_auto_20210325_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbc21',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
